### ISSUE TITLE
可以看一下您图片特征提取模型的训练数据吗？

### ISSUE THREAD

**Issue by skywd** [FuryMartin/Picf#12]
提取模型进行人物分类（或者聚类）时效果很差

**Comment by FuryMartin** [comment]
## 首先，我所采用的模型均是对应仓库的预训练模型，我没有进行额外的训练。
其中，人脸检测器采用的是 [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB](https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB) 中的 [RFB 模型](https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/tree/master/tf/export_models)，人脸对齐采用的是 Dlib 库预训练好的模型 [shape_predictor_68_face_landmarks.dat](http://dlib.net/files/) ，特征值提取采用的是 FaceNet 的预训练模型 [facenet_keras.h5](https://drive.google.com/drive/folders/1pwQ3H4aJ8a6yyJHZkTwtjcL4wYWQb7bn) 。

## 其次，我也存在分类效果很差的问题，我认为问题出在所采用的人脸检测器上。
我所采用的 [RFB 模型](https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/tree/master/tf/export_models)，检测速度很快，人脸的识别精度也很高，但是经过测试，会将一些非人脸物体标记为人脸，误报率大概有 7% 左右。我认为，正是这些非人脸的物体导致了分类结果的混乱，你可以通过尝试更换人脸检测器来解决这个问题。你可以对照一下本仓库和我参考过的原始仓库 [Sort-by-face](https://github.com/yashyenugu/Sort-By-Face) ，原仓库的识别分类效果似乎还是不错的。

**Comment by skywd** [comment]
> ## 首先，我所采用的模型均是对应仓库的预训练模型，我没有进行额外的训练。
> 其中，人脸检测器采用的是 [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB](https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB) 中的 [RFB 模型](https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/tree/master/tf/export_models)，人脸对齐采用的是 Dlib 库预训练好的模型 [shape_predictor_68_face_landmarks.dat](http://dlib.net/files/) ，特征值提取采用的是 FaceNet 的预训练模型 [facenet_keras.h5](https://drive.google.com/drive/folders/1pwQ3H4aJ8a6yyJHZkTwtjcL4wYWQb7bn) 。
> 
> ## 其次，我也存在分类效果很差的问题，我认为问题出在所采用的人脸检测器上。
> 我所采用的 [RFB 模型](https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/tree/master/tf/export_models)，检测速度很快，人脸的识别精度也很高，但是经过测试，会将一些非人脸物体标记为人脸（如下图所示），误报率大概有 7% 左右。
> 
> ![RFB_Trump_73](https://user-images.githubusercontent.com/41051953/149940118-77a0168e-9609-4174-af1f-4304db792cfd.jpeg)
> 
> 我认为，正是这些非人脸的物体导致了分类结果的混乱，你可以通过尝试更换人脸检测器来解决这个问题。你可以对照一下本仓库和我参考过的原始仓库 [Sort-by-face](https://github.com/yashyenugu/Sort-By-Face) ，原仓库所采用的检测器的分类效果似乎还是不错的，但是速度非常慢。

> ## 首先，我所采用的模型均是对应仓库的预训练模型，我没有进行额外的训练。
> 其中，人脸检测器采用的是 [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB](https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB) 中的 [RFB 模型](https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/tree/master/tf/export_models)，人脸对齐采用的是 Dlib 库预训练好的模型 [shape_predictor_68_face_landmarks.dat](http://dlib.net/files/) ，特征值提取采用的是 FaceNet 的预训练模型 [facenet_keras.h5](https://drive.google.com/drive/folders/1pwQ3H4aJ8a6yyJHZkTwtjcL4wYWQb7bn) 。
> 
> ## 其次，我也存在分类效果很差的问题，我认为问题出在所采用的人脸检测器上。
> 我所采用的 [RFB 模型](https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/tree/master/tf/export_models)，检测速度很快，人脸的识别精度也很高，但是经过测试，会将一些非人脸物体标记为人脸（如下图所示），误报率大概有 7% 左右。
> 
> ![RFB_Trump_73](https://user-images.githubusercontent.com/41051953/149940118-77a0168e-9609-4174-af1f-4304db792cfd.jpeg)
> 
> 我认为，正是这些非人脸的物体导致了分类结果的混乱，你可以通过尝试更换人脸检测器来解决这个问题。你可以对照一下本仓库和我参考过的原始仓库 [Sort-by-face](https://github.com/yashyenugu/Sort-By-Face) ，原仓库所采用的检测器的分类效果似乎还是不错的，但是速度非常慢。

非常感谢
