### ISSUE TITLE
关于预训练模型的问题

### ISSUE THREAD

**Issue by TendaG0** [FuryMartin/Picf#14]
大佬你好，我想学习一下你的代码，但是发现在模型加载的时候缺少两个，一个是facenet.h5 一个是RFB.h5模型，前者我已经找到，但是后者我找了很久都没有找到，想求助一下你，能不能上传一份RFB.h5的模型？

**Comment by FuryMartin** [comment]
模型比较大，所以我直接和代码打包扔在了Release里：[Picf v1.6](https://github.com/FuryMartin/Picf/releases/tag/v1.6)，你可以在页面里下载 [Picf_v1.6.zip](https://github.com/FuryMartin/Picf/releases/download/v1.6/Picf_v1.6.zip)。

**Comment by TendaG0** [comment]
> 模型比较大，所以我直接和代码打包扔在了Release里：[Picf v1.6](https://github.com/FuryMartin/Picf/releases/tag/v1.6)，你可以在页面里下载 [Picf_v1.6.zip](https://github.com/FuryMartin/Picf/releases/download/v1.6/Picf_v1.6.zip)。
谢谢！祝你天天开心！
